init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "6"

branches:
  only:
    - master

cache:
  - "node_modules -> package.json"
  - "app\\node_modules -> app\\package.json"
  - "%APPDATA%\\npm-cache"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run release:win
